local id = game.PlaceId

if id == 105626692504093 then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/veltrixkupal/Loader/refs/heads/main/be%20a%20Brainrot.lua.txt"))()
elseif id == 124473577469410 then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/veltrixkupal/Loader/refs/heads/main/be%20a%20lucky%20block.lua.txt"))()
elseif id == 1554960397 then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/veltrixkupal/Loader/refs/heads/main/car%20dealerships.lua.txt"))()
elseif id == 131667667758514 then
    loadstring(game:HttpGet("https://api.jnkie.com/api/v1/luascripts/public/d3ea11e8c8734eaf9058c24fc9059e3e07fcbc2a7841e84f65d75671d8bc9d22/download"))()
elseif id == 114640202062357 then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/veltrixkupal/Loader/refs/heads/main/Swing%20obby%20for%20brainrot.lua"))()
elseif id == 14259168147 then
    loadstring(game:HttpGet("https://vss.pandadevelopment.net/virtual/file/f5fe502b740a48c7"))()
elseif id == 286090429 then
    loadstring(game:HttpGet("https://vss.pandadevelopment.net/virtual/file/e1db028762944d1e"))()
else
    game.Players.LocalPlayer:Kick("This game is not supported.")
end
